# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mygallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygallery.Category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygallery.Location'),
        ),
    ]
